In [2]:
import pandas as pd
import numpy as np

In [17]:
# Form the adj matrix from the question like this.
A = [
        [0, 1, 0],
        [1, 0, 1],
        [0, 1, 0]
    ]

In [22]:
def linkNormalize(A):
    for i, row in enumerate(A):
        rowsum = sum(row)
        if rowsum>0:
            for j, elt in enumerate(row):
                A[i][j] /= rowsum
    return A

In [30]:
def getStohasticMatrix(A, alpha):
    n = len(A)
    H = linkNormalize(A)
    for i, row in enumerate(H):
        if sum(row)==0:
            H[i] = [1/n]*n
        else:
            for j, elt in enumerate(row):
                H[i][j] *= alpha
                H[i][j] += (1-alpha)/n
    G = [row[:] for row in H]
    return G

In [6]:
p0 = [1, 0, 0]

In [48]:
def calculatePageRankUsingIteration(p0, G):
    itr = 1
    pi = np.dot(p0, G)

    while not np.array_equal(p0, pi):
        p0 = pi
        pi = np.dot(p0, G)
        itr += 1
        # print(f" Itr: {itr}, pagerank = {pi}, prevpgrank = {p0}, sp = {sum(pi)}, spp = {sum(p0)}")
    print(f"PageRank converged at iteration {itr}")
    print(f"pagerank = {pi}, prevpgrank = {p0}")
    print(f"sp = {sum(pi)}, spp = {sum(p0)}")
    return pi

In [49]:
calculatePageRankUsingIteration(p0, G)

PageRank converged at iteration 117
pagerank = [0.31481481 0.37037037 0.31481481], prevpgrank = [0.31481481 0.37037037 0.31481481]
sp = 0.9999999999999865, spp = 0.9999999999999865


array([0.31481481, 0.37037037, 0.31481481])

In [58]:
def calculatePageRankUsingEV(G):
    G = np.array(G)
    w, v = np.linalg.eig(G.T)
    print(w, v)
    idx = np.argmax(w)
    
    EV = v[:, idx]
    compsum = sum(EV)
    for i, val in enumerate(EV):
        EV[i] = val/co

In [59]:
calculatePageRankUsingEV(G)

[ 1.00000000e+00 -4.50096173e-17 -1.25000000e-01] [[-5.43600057e-01 -7.07106781e-01  4.08248290e-01]
 [-6.39529479e-01 -6.96354930e-16 -8.16496581e-01]
 [-5.43600057e-01  7.07106781e-01  4.08248290e-01]]


array([-0.54360006, -0.63952948, -0.54360006])