In [145]:
import pandas as pd
import numpy as np

In [146]:
# Form the adj matrix from the question like this.
A = [
        [0, 1, 0],
        [1, 0, 1],
        [0, 1, 0]
    ]

In [147]:
def linkNormalize(A):
    for i, row in enumerate(A):
        rowsum = sum(row)
        if rowsum>0:
            for j, elt in enumerate(row):
                A[i][j] /= rowsum
    return A

In [148]:
def getStohasticMatrix(A, alpha):
    n = len(A)
    H = linkNormalize(A)
    for i, row in enumerate(H):
        if sum(row)==0:
            H[i] = [1/n]*n
        else:
            for j, elt in enumerate(row):
                H[i][j] *= alpha
                H[i][j] += (1-alpha)/n
    G = np.array(H)
    return G

In [149]:
G = getStohasticMatrix(A, 0.5)

In [150]:
p0 = [1, 0, 0]

In [156]:
def calculatePageRankUsingIteration(p0, G):
    itr = 1
    pi = np.dot(p0, G)

    while not np.array_equal(p0, pi):
        p0 = pi
        pi = np.dot(p0, G)
        itr += 1
        # print(f" Itr: {itr}, pagerank = {pi}, prevpgrank = {p0}, sp = {sum(pi)}, spp = {sum(p0)}")
    print(f"PageRank converged at iteration {itr}")
    print(f"pagerank = {pi}, prevpgrank = {p0}")
    print(f"sp = {sum(pi)}, spp = {sum(p0)}")
    return pi

In [157]:
calculatePageRankUsingIteration(p0, G)

PageRank converged at iteration 76
pagerank = [0.27777778 0.44444444 0.27777778], prevpgrank = [0.27777778 0.44444444 0.27777778]
sp = 0.9999999999999937, spp = 0.9999999999999937


array([0.27777778, 0.44444444, 0.27777778])

In [158]:
def calculatePageRankUsingEV(G):
    G = np.array(G)
    w, v = np.linalg.eig(G.T)
    idx = np.argmax(w)
    
    EV = v[:, idx]
    pr = np.divide(EV, np.sum(EV))

    return pr

In [159]:
G

array([[0.16666667, 0.66666667, 0.16666667],
       [0.41666667, 0.16666667, 0.41666667],
       [0.16666667, 0.66666667, 0.16666667]])

In [160]:
calculatePageRankUsingEV(G)

array([0.27777778, 0.44444444, 0.27777778])