In [1]:
import numpy as np
import copy

In [2]:
# pip install scipy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
processed_docs = ['reuters dataset reuters benchmark dataset',
 'reuters dataset class reuters class',
 'document multiple dataset document',
 'reuters document document class']

In [4]:
def TF(word, tf_map):
    return tf_map[word]

def DF(word, corpus_docmaps):
    count = 0
    
    for hm in corpus_docmaps:
        if word in hm:
            count += 1
    
    return count

def calculate_weights(doc, wordcount_map, corpus_docmaps):
    vector = [0]*len(wordcount_map)
    
    tf_map = {}
    
    for i in doc.split():
        if i in tf_map:
            tf_map[i] +=1
        else:
            tf_map[i] = 1
    
    for word in doc.split():
        TFik = TF(word, tf_map)
        LENi = sum([tf_map[key] for key in tf_map])
        N = len(corpus_docmaps)
        DFk = DF(word, corpus_docmaps)
        
        try:
            index = list(wordcount_map.keys()).index(word)
            vector[index] = (TFik/LENi)*np.log10((N+1)/(0.5+DFk))
        except ValueError:
            pass
    
    return vector

In [5]:
word_countmap = {}

for doc in processed_docs:
    for word in doc.split():
        if word in word_countmap:
            word_countmap[word] += 1
        else:
            word_countmap[word] = 1

corpus_docmaps = []

for doc in processed_docs:
    hm = {}
    
    for word in doc.split():
        if word in hm:
            hm[word] += 1
        else:
            hm[word] = 1
    
    corpus_docmaps.append(hm)


doc_matrix = []
for doc in processed_docs:
    vector = calculate_weights(doc, word_countmap, corpus_docmaps)
    doc_matrix.append(vector)
    
print(doc_matrix)

[[0.061960783994297275, 0.061960783994297275, 0.10457574905606754, 0, 0, 0], [0.061960783994297275, 0.030980391997148637, 0, 0.12041199826559248, 0, 0], [0, 0.0387254899964358, 0, 0, 0.1505149978319906, 0.1307196863200844], [0.0387254899964358, 0, 0, 0.0752574989159953, 0.1505149978319906, 0]]


In [19]:
doc_matrix

[[0.061960783994297275, 0.061960783994297275, 0.10457574905606754, 0, 0, 0],
 [0.061960783994297275, 0.030980391997148637, 0, 0.12041199826559248, 0, 0],
 [0, 0.0387254899964358, 0, 0, 0.1505149978319906, 0.1307196863200844],
 [0.0387254899964358, 0, 0, 0.0752574989159953, 0.1505149978319906, 0]]

In [6]:
A = np.array(doc_matrix)

In [7]:
A

array([[0.06196078, 0.06196078, 0.10457575, 0.        , 0.        ,
        0.        ],
       [0.06196078, 0.03098039, 0.        , 0.120412  , 0.        ,
        0.        ],
       [0.        , 0.03872549, 0.        , 0.        , 0.150515  ,
        0.13071969],
       [0.03872549, 0.        , 0.        , 0.0752575 , 0.150515  ,
        0.        ]])

In [8]:
from scipy.linalg import svd

In [9]:
U, singular, V_transpose = svd(A)

In [14]:
U, U.shape

(array([[ 0.10590786,  0.48741856, -0.83707353,  0.22475449],
        [ 0.20817907,  0.71593621,  0.28097206, -0.60427769],
        [ 0.74414148, -0.45097763, -0.27775407, -0.40709374],
        [ 0.62585818,  0.21558681,  0.37843796,  0.64699968]]),
 (4, 4))

In [15]:
singular

array([0.24692696, 0.16097876, 0.12803432, 0.07544964])

In [17]:
V_transpose, V_transpose.shape

(array([[ 0.17696625,  0.16939765,  0.04485291,  0.29226367,  0.83508701,
          0.39393811],
        [ 0.51503384,  0.21690123,  0.31663904,  0.63630651, -0.22009021,
         -0.36620765],
        [-0.15465609, -0.42111575, -0.6837041 ,  0.48668747,  0.11836228,
         -0.28357962],
        [ 0.02040864, -0.27249565,  0.3115173 , -0.31903008,  0.47858996,
         -0.70530705],
        [ 0.81629389, -0.13462596, -0.40388599, -0.38540548, -0.01731873,
          0.05982408],
        [ 0.11292632, -0.80903757,  0.4124436 ,  0.15004566, -0.10407726,
          0.35951406]]),
 (6, 6))

In [18]:
A.shape

(4, 6)